name: "Populate Cachix binary cache"
on:
  push:
    paths:
      - '**.nix'
      - '**.age'
      - 'pkgs/**'
      - 'flake.nix'
      - 'flake.lock'
      - '.github/workflows/*'
jobs:
  build-pkgs:
    name: Build custom Nix packages
    runs-on: ubuntu-latest

    strategy:
      matrix:
        name:
        - emacsPgtkGcc
        - grafanaDashboards/nginx
        - grafanaDashboards/node-exporter
        - kaleidoscope-udev-rules
        - sddm-sugar-candy
        - spot

    steps:
    - uses: actions/checkout@v2

    - uses: cachix/install-nix-action@v16

    - uses: cachix/cachix-action@v10
      with:
        name: alarsyo
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        extraPullNames: "nix-community"

    - name: Build package
      run: nix build --verbose -L .#"${{ matrix.name }}"

  build-configs:
    name: Build NixOS configurations
    runs-on: ubuntu-latest
    needs: [ build-pkgs ]

    strategy:
      matrix:
        name:
        - zephyrus

    steps:
    - uses: actions/checkout@v2

    - uses: cachix/install-nix-action@v16

    - uses: cachix/cachix-action@v10
      with:
        name: alarsyo
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        extraPullNames: "nix-community"

    - name: Build package
      run: nix build --verbose -L .#nixosConfigurations."${{ matrix.name }}".config.system.build.toplevel
