name: "Build everything and push to cachix"
on:
  workflow_dispatch:
  schedule:
    - cron: '* */1 * * *'
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09-small
    - uses: cachix/cachix-action@v8
      with:
        name: alarsyo
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build -E 'let pkgs = import <nixpkgs> { overlays = import ./overlays; }; in with pkgs; [ bitwarden_rs-postgresql bitwarden_rs-vault ]'
