name: "NUR"
on:
  push:
    branches:
      - 'main'
    paths:
      - 'pkgs/**'
      - '.github/workflows/*'

jobs:
  update-nur:
    name: "Ping NUR repo hook"
    runs-on: ubuntu-latest
    steps:
      - name: curl nur endpoint
        run: |
          curl -XPOST https://nur-update.herokuapp.com/update?repo=alarsyo
